### ISSUE TITLE
New release after #6 (Symfony components 3.0+)

### ISSUE THREAD

**Issue by miniche** [protobuf-php/protobuf-plugin#7]
Hi!

I'm starting to use your library with a Symfony 3 project. It seems that compatibility has been checked with the MR #6 (Add possibility to install newer version of components).

Do you have planned to create a new version / tag + packagist sync to use it?

**Comment by FabioBatSilva** [comment]
Done !

https://github.com/protobuf-php/protobuf-plugin/releases/tag/v0.1.3
https://packagist.org/packages/protobuf-php/protobuf-plugin#v0.1.3

**Comment by miniche** [comment]
Thanks @FabioBatSilva!
